server:
  port: 8082
  proxied: false
  limit: 10000
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "central"
  password: "secret"
  name: "central"
influxdb:
  scheme: "http"
  host: "localhost"
  port: 8086
  username: "root"
  password: "root"
  database: "central"
cache:
  address: "localhost:6379"
  password: ""
  database: 0
